export const STATUSES = ["New", "Pending", "Won", "Lost", "Canceled"] as const;
export const SOURCE_TYPES = [
  "Direct enquiry",
  "Team referral",
  "External client referral",
  "Partner",
  "Website",
  "LinkedIn",
  "Event",
  "PRF88",
  "Other",
] as const;
export const SERVICES = [
  "Scheduled Interpretation",
  "On-Demand Interpretation Hub",
  "Interpretation Equipment Rental",
  "Translation and Proofreading of Documents",
  "Transcription",
  "Voice Over",
  "Other service",
] as const;
export const INTERPRETATION_DELIVERIES = ["In-person", "Virtual"] as const;
export const INTERPRETATION_MODES = ["Consecutive", "Simultaneous"] as const;
export const MEETING_STAGES = [
  "No meeting yet",
  "Initial meeting",
  "Second / pitch meeting",
  "Close-the-deal meeting",
] as const;
export const FOLLOW_UP_ACTIONS = [
  "Call",
  "Email",
  "Send proposal",
  "Send presentation & price list",
  "Book meeting",
  "Follow up after no response",
  "Client check-in",
  "Other",
] as const;
export const OPPORTUNITY_TYPES = [
  "One-time project",
  "Recurring client",
  "Ongoing vendor relationship",
] as const;
export const ORGANIZATION_TYPES = [
  "Municipal Government",
  "State Government",
  "Non-Profit",
  "Education",
  "Healthcare",
  "Business",
  "Individual",
  "Other",
] as const;
export const ACTIVITY_TYPES = [
  "Note",
  "Triage call completed",
  "Presentation & price list emailed",
  "Proposal sent",
  "Meeting booked",
  "Follow-up completed",
] as const;
export const SATISFACTION_STATUSES = [
  "Healthy",
  "Needs attention",
  "At risk",
  "Expansion opportunity",
] as const;
export const RELATIONSHIP_TYPES = [
  "One-time client",
  "Recurring client",
  "Ongoing vendor relationship",
] as const;

export const FIELD_LIST_KEYS = [
  "statuses",
  "sourceTypes",
  "services",
  "interpretationDeliveries",
  "interpretationModes",
  "meetingStages",
  "followUpActions",
  "opportunityTypes",
  "organizationTypes",
  "activityTypes",
  "satisfactionStatuses",
  "relationshipTypes",
] as const;

export type FieldListKey = (typeof FIELD_LIST_KEYS)[number];

export const FIELD_LIST_DEFAULTS: Record<FieldListKey, readonly string[]> = {
  statuses: STATUSES,
  sourceTypes: SOURCE_TYPES,
  services: SERVICES,
  interpretationDeliveries: INTERPRETATION_DELIVERIES,
  interpretationModes: INTERPRETATION_MODES,
  meetingStages: MEETING_STAGES,
  followUpActions: FOLLOW_UP_ACTIONS,
  opportunityTypes: OPPORTUNITY_TYPES,
  organizationTypes: ORGANIZATION_TYPES,
  activityTypes: ACTIVITY_TYPES,
  satisfactionStatuses: SATISFACTION_STATUSES,
  relationshipTypes: RELATIONSHIP_TYPES,
};

export const FIELD_LIST_META: Record<FieldListKey, { title: string; description: string }> = {
  statuses: { title: "Lead statuses", description: "Dropdown choices for pipeline stage on sales records and the Client Care Status column." },
  sourceTypes: { title: "Source types", description: "Dropdown choices for how a lead first reached Rosetta." },
  services: { title: "Services", description: "Dropdown choices for service lines on new and edited sales records." },
  interpretationDeliveries: { title: "Interpretation delivery", description: "Dropdown choices for in-person or virtual delivery." },
  interpretationModes: { title: "Interpretation modes", description: "Dropdown choices for consecutive or simultaneous interpretation." },
  meetingStages: { title: "Meeting stages", description: "Dropdown choices for where the conversation stands with a lead." },
  followUpActions: { title: "Follow-up actions", description: "Dropdown choices for next actions on sales records and client care." },
  opportunityTypes: { title: "Opportunity types", description: "Dropdown choices for the kind of commercial relationship." },
  organizationTypes: { title: "Organization types", description: "Dropdown choices for the kind of organization behind a lead." },
  activityTypes: { title: "Activity types", description: "Dropdown choices for activity history on a sales record." },
  satisfactionStatuses: { title: "Satisfaction statuses", description: "Dropdown choices for client-care health ratings." },
  relationshipTypes: { title: "Relationship types", description: "Dropdown choices for how an active client works with Rosetta." },
};

export const DEFAULT_HISTORY_LOOKBACK_DAYS = 5;
export const MIN_HISTORY_LOOKBACK_DAYS = 1;
export const MAX_HISTORY_LOOKBACK_DAYS = 365;
export const MIN_REPORT_PRESET_DAYS = 1;
export const MAX_REPORT_PRESET_DAYS = 3650;

export type ReportPreset = {
  id: string;
  label: string;
  days: number;
};

export const DEFAULT_REPORT_PRESETS: ReportPreset[] = [
  { id: "last-7-days", label: "Download last 7 days", days: 7 },
  { id: "last-30-days", label: "Download last 30 days", days: 30 },
  { id: "last-90-days", label: "Download last 90 days", days: 90 },
];

export const DEFAULT_CUSTOM_REPORT_RANGE_ENABLED = true;
export const DEFAULT_SHOW_BACK_CONTROL = true;
export const DEFAULT_INCLUDE_WON_LEADS_IN_CLIENT_CARE = true;

export const UI_LABEL_GROUPS = [
  "chrome",
  "overview",
  "salesRecords",
  "clientCare",
  "forms",
  "history",
  "reports",
  "calendar",
  "team",
] as const;

export type UiLabelGroup = (typeof UI_LABEL_GROUPS)[number];

export const UI_LABEL_KEYS = [
  "productName",
  "tabOverview",
  "tabSalesRecords",
  "tabClientCare",
  "headingOverview",
  "headingSalesRecords",
  "headingClientCare",
  "ctaAddSalesRecord",
  "ctaAddClientFollowUp",
  "navDashboard",
  "navSettings",
  "navBack",
  "navTeamAccess",
  "navHistory",
  "navReports",
  "navAdminControls",
  "navSignOut",
  "eyebrowRosetta",
  "descOverview",
  "descSalesRecords",
  "descClientCare",
  "filterRequestReceivedBy",
  "filterPeriod",
  "periodAllTime",
  "periodLast90Days",
  "periodThisQuarter",
  "recordsShownSuffix",
  "metricBookedRevenue",
  "metricBookedRevenueHint",
  "metricOpenPipeline",
  "metricOpenPipelineHint",
  "metricFollowUpsDue",
  "metricFollowUpsDueHint",
  "metricClientCare",
  "metricClientCareHint",
  "queueEyebrow",
  "queueHeading",
  "queueReviewLeads",
  "queueEmpty",
  "queueActionUndefined",
  "followUpOverdue",
  "followUpDueToday",
  "followUpNext7",
  "followUpNoDate",
  "followUpScheduled",
  "circleEyebrow",
  "circleHeading",
  "circleEmpty",
  "donutServices",
  "careEyebrow",
  "careHeading",
  "careActiveSuffix",
  "careOpenButton",
  "pivotEyebrow",
  "pivotHeading",
  "pivotNote",
  "pivotColService",
  "pivotColLeads",
  "pivotColWon",
  "pivotColWinRate",
  "pivotColPipeline",
  "pivotColRevenue",
  "pivotEmpty",
  "importToolbarCopy",
  "importCsv",
  "exportCsv",
  "searchLeads",
  "searchPlaceholder",
  "filterAllLeads",
  "filterOverdue",
  "filterDueToday",
  "filterNext7Days",
  "filterNoFollowUpDate",
  "emptyLeads",
  "contactNotAdded",
  "actionNotSet",
  "notScheduled",
  "loadingWorkspace",
  "careSectionEyebrow",
  "careSectionHeading",
  "careSectionNote",
  "emptyClients",
  "notLinkedLead",
  "noExpansionNote",
  "linkedToPrefix",
  "wonLeadsInClientCareLabel",
  "wonLeadsInClientCareHint",
  "careWonLeadsNote",
  "formLeadWorkspace",
  "formUpdateSalesRecord",
  "formClientCare",
  "formUpdateClientFollowUp",
  "formCancel",
  "formSaveChanges",
  "formSaving",
  "sectionSalesLead",
  "sectionSalesContact",
  "sectionSalesService",
  "sectionSalesNext",
  "sectionCareRelationship",
  "sectionCareCheckin",
  "activityHistory",
  "activityEmpty",
  "activityAddNote",
  "activityAdding",
  "activityNotesHeading",
  "activityNotesHint",
  "firstActivityNote",
  "mergeHeading",
  "mergeCopy",
  "mergeDuplicateLabel",
  "mergeSelectPlaceholder",
  "mergeNote",
  "mergeAction",
  "mergeMerging",
  "optionalMark",
  "selectPlaceholder",
  "teamProductName",
  "teamEyebrow",
  "teamHeading",
  "teamCopy",
  "teamAddMember",
  "teamFieldName",
  "teamFieldEmail",
  "teamFieldRole",
  "teamFieldTempPassword",
  "teamRoleContributor",
  "teamRoleAdmin",
  "teamCreateAccount",
  "teamGeneratePassword",
  "teamAccounts",
  "teamEmpty",
  "teamChangePasswordEyebrow",
  "teamChangePasswordHeading",
  "teamCurrentPassword",
  "teamNewPassword",
  "teamChangePassword",
  "teamActive",
  "teamRemoved",
  "teamEditAccess",
  "teamResetPassword",
  "teamRemove",
  "teamSaveAccess",
  "teamCancel",
  "historyProductName",
  "historyEyebrow",
  "historyHeading",
  "historyCopy",
  "historyWindowHint",
  "historyEmpty",
  "historyLoading",
  "reportsProductName",
  "reportsEyebrow",
  "reportsHeading",
  "reportsCopy",
  "reportsNote",
  "reportsEmpty",
  "reportsLoading",
  "reportsDownloading",
  "reportsCustomHeading",
  "reportsCustomCopy",
  "reportsFromLabel",
  "reportsToLabel",
  "reportsCustomDownload",
  "reportsCustomInvalid",
  "reportsCustomReady",
  "adminTabCalendar",
  "calendarSectionEyebrow",
  "calendarSectionHeading",
  "calendarSectionCopy",
  "calendarEnableLabel",
  "calendarEnableHint",
  "calendarTargetEmailLabel",
  "calendarTargetEmailHint",
  "calendarIdLabel",
  "calendarIdHint",
  "calendarTimezoneLabel",
  "calendarTimezoneHint",
  "calendarTitleTemplateLabel",
  "calendarDescriptionTemplateLabel",
  "calendarTemplateHint",
  "calendarConnectButton",
  "calendarDisconnectButton",
  "calendarSaveButton",
  "calendarStatusConnected",
  "calendarStatusNotConnected",
  "calendarStatusNotConfigured",
  "calendarStatusEnabledDisconnected",
  "calendarStatusMismatch",
  "calendarLastErrorLabel",
  "calendarLastSyncLabel",
  "calendarConnectedAsPrefix",
  "calendarOauthHelp",
  "calendarTypeSales",
  "calendarTypeCare",
  "calendarConnectedNotice",
  "calendarDisconnectedNotice",
  "calendarConnectFailedNotice",
  "calendarSavedNotice",
] as const;

export type UiLabelKey = (typeof UI_LABEL_KEYS)[number];

export const DEFAULT_UI_LABELS: Record<UiLabelKey, string> = {
  productName: "Sales performance",
  tabOverview: "Overview",
  tabSalesRecords: "Sales records",
  tabClientCare: "Client care",
  headingOverview: "Sales performance",
  headingSalesRecords: "Sales records",
  headingClientCare: "Client care",
  ctaAddSalesRecord: "Add sales record",
  ctaAddClientFollowUp: "Add client follow-up",
  navDashboard: "Dashboard",
  navSettings: "Settings",
  navBack: "Back",
  navTeamAccess: "Team access",
  navHistory: "History",
  navReports: "Reports",
  navAdminControls: "Admin controls",
  navSignOut: "Sign out",
  eyebrowRosetta: "Rosetta Languages",
  descOverview: "Revenue performance and the team actions that need attention.",
  descSalesRecords: "Lead details, contacts, meetings, and the next required action.",
  descClientCare: "Protect active relationships and create the next opportunity.",
  filterRequestReceivedBy: "Request received by",
  filterPeriod: "Period",
  periodAllTime: "All time",
  periodLast90Days: "Last 90 days",
  periodThisQuarter: "This quarter",
  recordsShownSuffix: "shown",
  metricBookedRevenue: "Booked revenue",
  metricBookedRevenueHint: "won deals",
  metricOpenPipeline: "Open pipeline",
  metricOpenPipelineHint: "active opportunities",
  metricFollowUpsDue: "Follow-ups due",
  metricFollowUpsDueHint: "Overdue, today, or due this week",
  metricClientCare: "Client care attention",
  metricClientCareHint: "Relationships needing a check-in",
  queueEyebrow: "Priority worklist",
  queueHeading: "Follow-up queue",
  queueReviewLeads: "Review leads",
  queueEmpty: "No follow-ups are due in the next seven days.",
  queueActionUndefined: "Action to be defined",
  followUpOverdue: "Overdue",
  followUpDueToday: "Due today",
  followUpNext7: "Next 7 days",
  followUpNoDate: "No date",
  followUpScheduled: "Scheduled",
  circleEyebrow: "Full-circle view",
  circleHeading: "Booked revenue by service",
  circleEmpty: "Won work will appear here as the team records it.",
  donutServices: "services",
  careEyebrow: "Relationship health",
  careHeading: "Client satisfaction pipeline",
  careActiveSuffix: "active client follow-ups",
  careOpenButton: "Open client care",
  pivotEyebrow: "Performance pivot",
  pivotHeading: "Service performance",
  pivotNote: "A shared view of lead volume, active pipeline, conversion, and booked revenue.",
  pivotColService: "Service",
  pivotColLeads: "Leads",
  pivotColWon: "Won",
  pivotColWinRate: "Win rate",
  pivotColPipeline: "Open pipeline",
  pivotColRevenue: "Booked revenue",
  pivotEmpty: "Add sales records to build the performance pivot.",
  importToolbarCopy: "Import a cleaned sales pipeline CSV, or export the current records for reporting.",
  importCsv: "Import CSV",
  exportCsv: "Export CSV",
  searchLeads: "Search leads",
  searchPlaceholder: "Search name or phone number",
  filterAllLeads: "All leads",
  filterOverdue: "Overdue",
  filterDueToday: "Due today",
  filterNext7Days: "Next 7 days",
  filterNoFollowUpDate: "No follow-up date",
  emptyLeads: "No lead matches this worklist.",
  contactNotAdded: "Contact not added",
  actionNotSet: "Action not set",
  notScheduled: "Not scheduled",
  loadingWorkspace: "Loading Rosetta's workspace...",
  careSectionEyebrow: "Post-conversion pipeline",
  careSectionHeading: "Client satisfaction follow-ups",
  careSectionNote: "Keep a visible cadence with clients and note the next opportunity to support them.",
  emptyClients: "Add a converted client to begin the satisfaction follow-up pipeline.",
  notLinkedLead: "Not linked to a sales record",
  noExpansionNote: "No expansion note",
  linkedToPrefix: "Linked to",
  wonLeadsInClientCareLabel: "Show / auto-add Won leads in Client Care",
  wonLeadsInClientCareHint: "When on, every Won sales record gets a client-care row if it does not already have one, and Client Care stays Won-only: changing a lead away from Won removes that linked care row. Turning this off stops adding new Won leads and stops auto-removing rows when a lead leaves Won. Existing care records then stay until you delete them.",
  careWonLeadsNote: "Won leads are added here automatically. Changing a lead away from Won removes that care record.",
  formLeadWorkspace: "Lead workspace",
  formUpdateSalesRecord: "Update sales record",
  formClientCare: "Client care",
  formUpdateClientFollowUp: "Update client follow-up",
  formCancel: "Cancel",
  formSaveChanges: "Save changes",
  formSaving: "Saving...",
  sectionSalesLead: "Lead and referral",
  sectionSalesContact: "Contact person",
  sectionSalesService: "Service and opportunity",
  sectionSalesNext: "Meetings and next step",
  sectionCareRelationship: "Relationship",
  sectionCareCheckin: "Satisfaction check-in",
  activityHistory: "Activity history",
  activityEmpty: "No activity yet. Add the first update above.",
  activityAddNote: "Add Note",
  activityAdding: "Adding...",
  activityNotesHeading: "Activity notes",
  activityNotesHint: "Each note is saved as its own dated box.",
  firstActivityNote: "First activity note",
  mergeHeading: "Merge duplicate lead",
  mergeCopy: "will remain as the main record. Choose the duplicate entry to combine into it.",
  mergeDuplicateLabel: "Duplicate record",
  mergeSelectPlaceholder: "Select duplicate record",
  mergeNote: "The duplicate's activity notes and client-care follow-ups move to the main record. Empty contact fields on the main record are filled from the duplicate.",
  mergeAction: "Merge records",
  mergeMerging: "Merging...",
  optionalMark: "Optional",
  selectPlaceholder: "Select",
  teamProductName: "Team access",
  teamEyebrow: "Admin controls",
  teamHeading: "Team access",
  teamCopy: "Each person signs in with their own email and password. Contributors can only add new sales records.",
  teamAddMember: "Add team member",
  teamFieldName: "Name",
  teamFieldEmail: "Business email",
  teamFieldRole: "Access role",
  teamFieldTempPassword: "Temporary password",
  teamRoleContributor: "Contributor - add leads only",
  teamRoleAdmin: "Admin - full dashboard access",
  teamCreateAccount: "Create account",
  teamGeneratePassword: "Generate temporary password",
  teamAccounts: "Accounts",
  teamEmpty: "No accounts have been added yet.",
  teamChangePasswordEyebrow: "Your account",
  teamChangePasswordHeading: "Change your password",
  teamCurrentPassword: "Current password",
  teamNewPassword: "New password",
  teamChangePassword: "Change password",
  teamActive: "Active",
  teamRemoved: "Removed",
  teamEditAccess: "Edit access",
  teamResetPassword: "Reset password",
  teamRemove: "Remove",
  teamSaveAccess: "Save access",
  teamCancel: "Cancel",
  historyProductName: "Change history",
  historyEyebrow: "Audit log",
  historyHeading: "Change history",
  historyCopy: "User edits to sales records, client care, and team access, newest first.",
  historyWindowHint: "Showing the last {days} days.",
  historyEmpty: "No dashboard changes in this window.",
  historyLoading: "Loading change history...",
  reportsProductName: "Reports",
  reportsEyebrow: "CSV download",
  reportsHeading: "Reports",
  reportsCopy: "Download sales records whose Lead date falls in a selected window.",
  reportsNote: "Each CSV uses the same columns as Export CSV on Sales records. Ranges are filtered by Lead date. Client-care follow-ups are not included.",
  reportsEmpty: "No report ranges are configured. Add ranges in Admin controls.",
  reportsLoading: "Loading reports...",
  reportsDownloading: "Preparing CSV...",
  reportsCustomHeading: "Custom date range",
  reportsCustomCopy: "Choose a From date and a To date. The CSV includes sales records whose Lead date falls in that window, including both dates.",
  reportsFromLabel: "From",
  reportsToLabel: "To",
  reportsCustomDownload: "Download custom range",
  reportsCustomInvalid: "Choose a From date and a To date, with From on or before To.",
  reportsCustomReady: "Custom range CSV is ready.",
  adminTabCalendar: "Calendar",
  calendarSectionEyebrow: "Integrations",
  calendarSectionHeading: "Google Calendar sync",
  calendarSectionCopy: "Every follow-up date on Sales records and Client care syncs to one Google Calendar. Connect Danyal's account, edit the templates, then turn sync on. Saving a lead still works if Google is disconnected.",
  calendarEnableLabel: "Sync follow-up dates to Google Calendar",
  calendarEnableHint: "Leave this off until Google is connected. Default is off.",
  calendarTargetEmailLabel: "Target Google account",
  calendarTargetEmailHint: "Who should receive the events. Default is danyal@rosettalanguages.org. Change it here without a code change.",
  calendarIdLabel: "Calendar ID",
  calendarIdHint: "Use primary for the connected account's main calendar, or paste a calendar ID from Google Calendar settings.",
  calendarTimezoneLabel: "Timezone",
  calendarTimezoneHint: "Follow-up fields are dates only, so events are all-day in this timezone.",
  calendarTitleTemplateLabel: "Event title template",
  calendarDescriptionTemplateLabel: "Event description template",
  calendarTemplateHint: "Placeholders: {name} {action} {date} {type} {stage} {service} {company} {context}",
  calendarConnectButton: "Connect Google Calendar",
  calendarDisconnectButton: "Disconnect Google",
  calendarSaveButton: "Save calendar settings",
  calendarStatusConnected: "Connected",
  calendarStatusNotConnected: "Not connected",
  calendarStatusNotConfigured: "Google OAuth is not configured on this Worker",
  calendarStatusEnabledDisconnected: "Sync is on, but Google Calendar is not connected. Follow-up saves still work.",
  calendarStatusMismatch: "Connected Google account does not match the target email. Events still go to the connected account.",
  calendarLastErrorLabel: "Last sync error",
  calendarLastSyncLabel: "Last successful sync",
  calendarConnectedAsPrefix: "Connected as",
  calendarOauthHelp: "A developer must set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET as Worker secrets. See GOOGLE_CALENDAR_SETUP.md. After that, admins connect and enable sync here.",
  calendarTypeSales: "Sales follow-up",
  calendarTypeCare: "Client-care follow-up",
  calendarConnectedNotice: "Google Calendar is connected. Turn sync on to start creating events.",
  calendarDisconnectedNotice: "Google Calendar is disconnected. Sync is off until you connect again and turn it on.",
  calendarConnectFailedNotice: "Google Calendar could not be connected.",
  calendarSavedNotice: "Calendar settings saved. The next follow-up save uses these templates.",
};

export const UI_LABEL_META: Record<UiLabelKey, { title: string; hint: string; group: UiLabelGroup }> = {
  productName: { group: "chrome", title: "Top bar product name", hint: "Shown next to the Rosetta logo on the dashboard." },
  tabOverview: { group: "chrome", title: "Overview tab", hint: "First dashboard tab." },
  tabSalesRecords: { group: "chrome", title: "Sales records tab", hint: "Second dashboard tab." },
  tabClientCare: { group: "chrome", title: "Client care tab", hint: "Third dashboard tab." },
  headingOverview: { group: "overview", title: "Overview heading", hint: "Main heading on the Overview tab." },
  headingSalesRecords: { group: "salesRecords", title: "Sales records heading", hint: "Main heading on the Sales records tab." },
  headingClientCare: { group: "clientCare", title: "Client care heading", hint: "Main heading on the Client care tab." },
  ctaAddSalesRecord: { group: "chrome", title: "Add sales record button", hint: "Primary button on Overview and Sales records." },
  ctaAddClientFollowUp: { group: "chrome", title: "Add client follow-up button", hint: "Primary button on Client care." },
  navDashboard: { group: "chrome", title: "Dashboard link", hint: "Settings menu link back to the dashboard." },
  navSettings: { group: "chrome", title: "Settings button", hint: "Top-bar button that opens the Settings menu." },
  navBack: { group: "chrome", title: "Back button", hint: "Shown on History, Reports, Team access, and Admin controls. Visibility is under History & reports." },
  navTeamAccess: { group: "chrome", title: "Team access menu item", hint: "Settings menu link to Team access." },
  navHistory: { group: "chrome", title: "History menu item", hint: "Settings menu link to Change history." },
  navReports: { group: "chrome", title: "Reports menu item", hint: "Settings menu link to Reports." },
  navAdminControls: { group: "chrome", title: "Admin controls menu item", hint: "Settings menu link to this control center." },
  navSignOut: { group: "chrome", title: "Sign out menu item", hint: "Settings menu sign-out action." },
  eyebrowRosetta: { group: "chrome", title: "Page eyebrow", hint: "Small uppercase line above page headings." },
  descOverview: { group: "overview", title: "Overview description", hint: "Supporting sentence under the Overview heading." },
  descSalesRecords: { group: "salesRecords", title: "Sales records description", hint: "Supporting sentence under the Sales records heading." },
  descClientCare: { group: "clientCare", title: "Client care description", hint: "Supporting sentence under the Client care heading." },
  filterRequestReceivedBy: { group: "overview", title: "Request-received filter label", hint: "Overview filter for who received the request." },
  filterPeriod: { group: "overview", title: "Period filter label", hint: "Overview time-range filter." },
  periodAllTime: { group: "overview", title: "All-time period", hint: "First period option." },
  periodLast90Days: { group: "overview", title: "Last 90 days period", hint: "Second period option." },
  periodThisQuarter: { group: "overview", title: "This quarter period", hint: "Third period option." },
  recordsShownSuffix: { group: "overview", title: "Records-shown suffix", hint: "Appears after the visible record count." },
  metricBookedRevenue: { group: "overview", title: "Booked revenue metric", hint: "First Overview metric card title." },
  metricBookedRevenueHint: { group: "overview", title: "Booked revenue hint", hint: "Small text under booked revenue." },
  metricOpenPipeline: { group: "overview", title: "Open pipeline metric", hint: "Second Overview metric card title." },
  metricOpenPipelineHint: { group: "overview", title: "Open pipeline hint", hint: "Small text under open pipeline." },
  metricFollowUpsDue: { group: "overview", title: "Follow-ups due metric", hint: "Third Overview metric card title." },
  metricFollowUpsDueHint: { group: "overview", title: "Follow-ups due hint", hint: "Small text under follow-ups due." },
  metricClientCare: { group: "overview", title: "Client care metric", hint: "Fourth Overview metric card title." },
  metricClientCareHint: { group: "overview", title: "Client care hint", hint: "Small text under client care attention." },
  queueEyebrow: { group: "overview", title: "Follow-up queue eyebrow", hint: "Small label above the follow-up queue." },
  queueHeading: { group: "overview", title: "Follow-up queue heading", hint: "Follow-up queue title." },
  queueReviewLeads: { group: "overview", title: "Review leads link", hint: "Link from the queue to the Sales records tab." },
  queueEmpty: { group: "overview", title: "Empty follow-up queue", hint: "Shown when nothing is due in the next seven days." },
  queueActionUndefined: { group: "overview", title: "Undefined queue action", hint: "Shown when a queued lead has no next action." },
  followUpOverdue: { group: "overview", title: "Overdue follow-up label", hint: "Used on the queue and lead table." },
  followUpDueToday: { group: "overview", title: "Due today label", hint: "Used on the queue and lead table." },
  followUpNext7: { group: "overview", title: "Next 7 days label", hint: "Used on the queue and lead table." },
  followUpNoDate: { group: "overview", title: "No date label", hint: "Used when a follow-up date is missing." },
  followUpScheduled: { group: "overview", title: "Scheduled follow-up label", hint: "Used for later follow-up dates." },
  circleEyebrow: { group: "overview", title: "Revenue circle eyebrow", hint: "Small label above booked revenue by service." },
  circleHeading: { group: "overview", title: "Revenue circle heading", hint: "Booked revenue by service title." },
  circleEmpty: { group: "overview", title: "Empty revenue circle", hint: "Shown when there is no won work yet." },
  donutServices: { group: "overview", title: "Donut center label", hint: "Word under the service count in the donut." },
  careEyebrow: { group: "overview", title: "Satisfaction pipeline eyebrow", hint: "Small label on the Overview client-care card." },
  careHeading: { group: "overview", title: "Satisfaction pipeline heading", hint: "Overview client-care card title." },
  careActiveSuffix: { group: "overview", title: "Active follow-ups suffix", hint: "Text next to the active follow-up count." },
  careOpenButton: { group: "overview", title: "Open client care button", hint: "Button on the Overview client-care card." },
  pivotEyebrow: { group: "overview", title: "Service pivot eyebrow", hint: "Small label above the service performance table." },
  pivotHeading: { group: "overview", title: "Service pivot heading", hint: "Service performance table title." },
  pivotNote: { group: "overview", title: "Service pivot note", hint: "Sentence under the service performance heading." },
  pivotColService: { group: "overview", title: "Pivot column: service", hint: "First service-performance column." },
  pivotColLeads: { group: "overview", title: "Pivot column: leads", hint: "Second service-performance column." },
  pivotColWon: { group: "overview", title: "Pivot column: won", hint: "Third service-performance column." },
  pivotColWinRate: { group: "overview", title: "Pivot column: win rate", hint: "Fourth service-performance column." },
  pivotColPipeline: { group: "overview", title: "Pivot column: pipeline", hint: "Fifth service-performance column." },
  pivotColRevenue: { group: "overview", title: "Pivot column: revenue", hint: "Sixth service-performance column." },
  pivotEmpty: { group: "overview", title: "Empty service pivot", hint: "Shown when the service table has no rows." },
  importToolbarCopy: { group: "salesRecords", title: "Import / export sentence", hint: "Copy above Import CSV and Export CSV. Do not put teammate names here." },
  importCsv: { group: "salesRecords", title: "Import CSV button", hint: "Sales records toolbar." },
  exportCsv: { group: "salesRecords", title: "Export CSV button", hint: "Sales records toolbar." },
  searchLeads: { group: "salesRecords", title: "Search leads label", hint: "Search field label on Sales records." },
  searchPlaceholder: { group: "salesRecords", title: "Search placeholder", hint: "Placeholder inside the lead search box." },
  filterAllLeads: { group: "salesRecords", title: "All leads chip", hint: "First worklist filter chip." },
  filterOverdue: { group: "salesRecords", title: "Overdue chip", hint: "Second worklist filter chip." },
  filterDueToday: { group: "salesRecords", title: "Due today chip", hint: "Third worklist filter chip." },
  filterNext7Days: { group: "salesRecords", title: "Next 7 days chip", hint: "Fourth worklist filter chip." },
  filterNoFollowUpDate: { group: "salesRecords", title: "No follow-up date chip", hint: "Fifth worklist filter chip." },
  emptyLeads: { group: "salesRecords", title: "Empty sales records table", hint: "Shown when no lead matches the worklist." },
  contactNotAdded: { group: "salesRecords", title: "Missing contact fallback", hint: "Shown when a lead has no contact or company." },
  actionNotSet: { group: "salesRecords", title: "Missing action fallback", hint: "Shown when next action is empty." },
  notScheduled: { group: "salesRecords", title: "Missing date fallback", hint: "Shown when a date is empty." },
  loadingWorkspace: { group: "chrome", title: "Loading message", hint: "Shown while the dashboard loads." },
  careSectionEyebrow: { group: "clientCare", title: "Client care table eyebrow", hint: "Small label above the client-care table." },
  careSectionHeading: { group: "clientCare", title: "Client care table heading", hint: "Heading above the client-care table." },
  careSectionNote: { group: "clientCare", title: "Client care table note", hint: "Sentence under the client-care table heading." },
  emptyClients: { group: "clientCare", title: "Empty client-care table", hint: "Shown when there are no client follow-ups." },
  notLinkedLead: { group: "clientCare", title: "Unlinked client fallback", hint: "Shown when a follow-up is not linked to a lead." },
  noExpansionNote: { group: "clientCare", title: "Missing expansion fallback", hint: "Shown when expansion opportunity is empty." },
  linkedToPrefix: { group: "clientCare", title: "Linked lead prefix", hint: "Appears before the linked lead name." },
  wonLeadsInClientCareLabel: { group: "clientCare", title: "Won leads admin toggle", hint: "Checkbox label under History & reports for auto-adding Won leads to Client care and removing them when they leave Won." },
  wonLeadsInClientCareHint: { group: "clientCare", title: "Won leads admin hint", hint: "Help text under the Won-leads Client care toggle." },
  careWonLeadsNote: { group: "clientCare", title: "Won leads table note", hint: "Shown under the Client care table heading when the Won-leads toggle is on." },
  formLeadWorkspace: { group: "forms", title: "Sales form eyebrow", hint: "Small label on the add/edit sales record modal." },
  formUpdateSalesRecord: { group: "forms", title: "Update sales record title", hint: "Modal title when editing a sales record." },
  formClientCare: { group: "forms", title: "Client form eyebrow", hint: "Small label on the client follow-up modal." },
  formUpdateClientFollowUp: { group: "forms", title: "Update client follow-up title", hint: "Modal title when editing a client follow-up." },
  formCancel: { group: "forms", title: "Cancel button", hint: "Modal cancel action." },
  formSaveChanges: { group: "forms", title: "Save changes button", hint: "Modal save action when editing." },
  formSaving: { group: "forms", title: "Saving label", hint: "Shown on buttons while a form saves." },
  sectionSalesLead: { group: "forms", title: "Sales section: lead", hint: "First sales-record form section." },
  sectionSalesContact: { group: "forms", title: "Sales section: contact", hint: "Second sales-record form section." },
  sectionSalesService: { group: "forms", title: "Sales section: service", hint: "Third sales-record form section." },
  sectionSalesNext: { group: "forms", title: "Sales section: next step", hint: "Fourth sales-record form section." },
  sectionCareRelationship: { group: "forms", title: "Care section: relationship", hint: "First client-care form section." },
  sectionCareCheckin: { group: "forms", title: "Care section: check-in", hint: "Second client-care form section." },
  activityHistory: { group: "forms", title: "Activity history heading", hint: "Activity modal title." },
  activityEmpty: { group: "forms", title: "Empty activity list", hint: "Shown when a lead has no activities." },
  activityAddNote: { group: "forms", title: "Add activity button", hint: "Button that saves a new activity note." },
  activityAdding: { group: "forms", title: "Adding activity label", hint: "Shown while an activity saves." },
  activityNotesHeading: { group: "forms", title: "Activity notes heading", hint: "Heading on the edit-record notes box." },
  activityNotesHint: { group: "forms", title: "Activity notes hint", hint: "Sentence in the edit-record notes box." },
  firstActivityNote: { group: "forms", title: "First activity note label", hint: "Fallback label for the create-record note field." },
  mergeHeading: { group: "forms", title: "Merge modal heading", hint: "Title of the merge-duplicate dialog." },
  mergeCopy: { group: "forms", title: "Merge modal sentence", hint: "Follows the primary lead name." },
  mergeDuplicateLabel: { group: "forms", title: "Duplicate record label", hint: "Label on the merge dropdown." },
  mergeSelectPlaceholder: { group: "forms", title: "Merge placeholder", hint: "First option in the merge dropdown." },
  mergeNote: { group: "forms", title: "Merge help text", hint: "Explains what merge keeps and moves." },
  mergeAction: { group: "forms", title: "Merge button", hint: "Confirms a merge." },
  mergeMerging: { group: "forms", title: "Merging label", hint: "Shown while records merge." },
  optionalMark: { group: "forms", title: "Optional marker", hint: "Shown next to fields that are not required." },
  selectPlaceholder: { group: "forms", title: "Select placeholder", hint: "Empty choice on optional dropdowns." },
  teamProductName: { group: "team", title: "Team top-bar name", hint: "Product name on the Team access page." },
  teamEyebrow: { group: "team", title: "Team page eyebrow", hint: "Small label above Team access." },
  teamHeading: { group: "team", title: "Team page heading", hint: "Main Team access heading." },
  teamCopy: { group: "team", title: "Team page description", hint: "Sentence under the Team access heading." },
  teamAddMember: { group: "team", title: "Add team member heading", hint: "Heading on the create-account form." },
  teamFieldName: { group: "team", title: "Name field", hint: "Create-account name label." },
  teamFieldEmail: { group: "team", title: "Email field", hint: "Create-account email label." },
  teamFieldRole: { group: "team", title: "Role field", hint: "Create-account role label." },
  teamFieldTempPassword: { group: "team", title: "Temporary password field", hint: "Create-account password label." },
  teamRoleContributor: { group: "team", title: "Contributor role option", hint: "Dropdown option for contributor access." },
  teamRoleAdmin: { group: "team", title: "Admin role option", hint: "Dropdown option for administrator access." },
  teamCreateAccount: { group: "team", title: "Create account button", hint: "Submits a new account." },
  teamGeneratePassword: { group: "team", title: "Generate password button", hint: "Fills a random temporary password." },
  teamAccounts: { group: "team", title: "Accounts heading", hint: "Heading above the account list." },
  teamEmpty: { group: "team", title: "Empty accounts list", hint: "Shown when no accounts exist." },
  teamChangePasswordEyebrow: { group: "team", title: "Your account eyebrow", hint: "Small label on the change-password panel." },
  teamChangePasswordHeading: { group: "team", title: "Change password heading", hint: "Heading on the change-password panel." },
  teamCurrentPassword: { group: "team", title: "Current password field", hint: "Label for the signed-in admin's current password." },
  teamNewPassword: { group: "team", title: "New password field", hint: "Label for the signed-in admin's new password." },
  teamChangePassword: { group: "team", title: "Change password button", hint: "Saves the signed-in admin's new password." },
  teamActive: { group: "team", title: "Active status", hint: "Badge for an active account." },
  teamRemoved: { group: "team", title: "Removed status", hint: "Badge for a removed account." },
  teamEditAccess: { group: "team", title: "Edit access button", hint: "Opens the role editor for an account." },
  teamResetPassword: { group: "team", title: "Reset password button", hint: "Opens password reset for an account." },
  teamRemove: { group: "team", title: "Remove account button", hint: "Removes an account's access." },
  teamSaveAccess: { group: "team", title: "Save access button", hint: "Saves a role change." },
  teamCancel: { group: "team", title: "Team cancel button", hint: "Cancels a role edit." },
  historyProductName: { group: "history", title: "History top-bar name", hint: "Product name on the History page." },
  historyEyebrow: { group: "history", title: "History page eyebrow", hint: "Small label above Change history." },
  historyHeading: { group: "history", title: "History page heading", hint: "Main History heading." },
  historyCopy: { group: "history", title: "History page description", hint: "Sentence under the History heading." },
  historyWindowHint: { group: "history", title: "History window hint", hint: "Shown under the description. Use {days} for the lookback number from History & reports." },
  historyEmpty: { group: "history", title: "Empty history", hint: "Shown when nothing was changed in the lookback window." },
  historyLoading: { group: "history", title: "History loading message", hint: "Shown while history loads." },
  reportsProductName: { group: "reports", title: "Reports top-bar name", hint: "Product name on the Reports page." },
  reportsEyebrow: { group: "reports", title: "Reports page eyebrow", hint: "Small label above Reports." },
  reportsHeading: { group: "reports", title: "Reports page heading", hint: "Main Reports heading." },
  reportsCopy: { group: "reports", title: "Reports page description", hint: "Sentence under the Reports heading." },
  reportsNote: { group: "reports", title: "Reports help text", hint: "Explains Lead date filtering and that client care is not in the CSV." },
  reportsEmpty: { group: "reports", title: "Empty reports", hint: "Shown when no download ranges are configured." },
  reportsLoading: { group: "reports", title: "Reports loading message", hint: "Shown while reports load." },
  reportsDownloading: { group: "reports", title: "Reports downloading label", hint: "Shown on a button while a CSV downloads." },
  reportsCustomHeading: { group: "reports", title: "Custom range heading", hint: "Heading above the From and To date inputs." },
  reportsCustomCopy: { group: "reports", title: "Custom range help text", hint: "Explains the inclusive Lead-date window for a custom CSV." },
  reportsFromLabel: { group: "reports", title: "From date label", hint: "Label on the custom range start date." },
  reportsToLabel: { group: "reports", title: "To date label", hint: "Label on the custom range end date." },
  reportsCustomDownload: { group: "reports", title: "Custom range download button", hint: "Downloads the CSV for the chosen From–To window." },
  reportsCustomInvalid: { group: "reports", title: "Custom range validation error", hint: "Shown when From or To is missing, or From is after To." },
  reportsCustomReady: { group: "reports", title: "Custom range ready message", hint: "Shown after a custom-range CSV downloads." },
  adminTabCalendar: { group: "calendar", title: "Admin Calendar tab", hint: "Tab name on Admin controls." },
  calendarSectionEyebrow: { group: "calendar", title: "Calendar eyebrow", hint: "Small label above Google Calendar sync." },
  calendarSectionHeading: { group: "calendar", title: "Calendar heading", hint: "Main Calendar tab heading." },
  calendarSectionCopy: { group: "calendar", title: "Calendar description", hint: "Sentence under the Calendar heading." },
  calendarEnableLabel: { group: "calendar", title: "Enable sync checkbox", hint: "Turns follow-up calendar sync on or off." },
  calendarEnableHint: { group: "calendar", title: "Enable sync hint", hint: "Shown under the enable checkbox." },
  calendarTargetEmailLabel: { group: "calendar", title: "Target account label", hint: "Label for the Google account email field." },
  calendarTargetEmailHint: { group: "calendar", title: "Target account hint", hint: "Explains the default Danyal account." },
  calendarIdLabel: { group: "calendar", title: "Calendar ID label", hint: "Label for the calendar id field." },
  calendarIdHint: { group: "calendar", title: "Calendar ID hint", hint: "Explains primary vs a pasted calendar id." },
  calendarTimezoneLabel: { group: "calendar", title: "Timezone label", hint: "Label for the timezone field." },
  calendarTimezoneHint: { group: "calendar", title: "Timezone hint", hint: "Explains all-day events." },
  calendarTitleTemplateLabel: { group: "calendar", title: "Title template label", hint: "Label for the event title template." },
  calendarDescriptionTemplateLabel: { group: "calendar", title: "Description template label", hint: "Label for the event description template." },
  calendarTemplateHint: { group: "calendar", title: "Template placeholder hint", hint: "Lists {name} {action} {date} and the other placeholders." },
  calendarConnectButton: { group: "calendar", title: "Connect button", hint: "Starts the Google OAuth flow." },
  calendarDisconnectButton: { group: "calendar", title: "Disconnect button", hint: "Disconnects Google Calendar." },
  calendarSaveButton: { group: "calendar", title: "Save calendar button", hint: "Saves enable, email, calendar id, timezone, and templates." },
  calendarStatusConnected: { group: "calendar", title: "Connected status", hint: "Shown when Google is connected." },
  calendarStatusNotConnected: { group: "calendar", title: "Not connected status", hint: "Shown when Google is not connected." },
  calendarStatusNotConfigured: { group: "calendar", title: "Not configured status", hint: "Shown when Worker secrets are missing." },
  calendarStatusEnabledDisconnected: { group: "calendar", title: "Enabled but disconnected status", hint: "Shown when sync is on without a Google connection." },
  calendarStatusMismatch: { group: "calendar", title: "Account mismatch status", hint: "Shown when the connected Google email differs from the target email." },
  calendarLastErrorLabel: { group: "calendar", title: "Last error label", hint: "Label above the last Google API error." },
  calendarLastSyncLabel: { group: "calendar", title: "Last sync label", hint: "Label above the last successful sync time." },
  calendarConnectedAsPrefix: { group: "calendar", title: "Connected-as prefix", hint: "Appears before the connected Google email." },
  calendarOauthHelp: { group: "calendar", title: "OAuth setup help", hint: "Shown when Worker secrets are missing." },
  calendarTypeSales: { group: "calendar", title: "Sales event type", hint: "Fills {type} on sales follow-up events." },
  calendarTypeCare: { group: "calendar", title: "Client-care event type", hint: "Fills {type} on client-care follow-up events." },
  calendarConnectedNotice: { group: "calendar", title: "Connected notice", hint: "Shown after a successful Google connect." },
  calendarDisconnectedNotice: { group: "calendar", title: "Disconnected notice", hint: "Shown after Google is disconnected." },
  calendarConnectFailedNotice: { group: "calendar", title: "Connect failed notice", hint: "Shown if Google OAuth fails." },
  calendarSavedNotice: { group: "calendar", title: "Settings saved notice", hint: "Shown after calendar settings save." },
};

export const UI_LABEL_GROUP_META: Record<UiLabelGroup, { title: string; description: string }> = {
  chrome: { title: "Navigation and chrome", description: "Settings menu, Back button, tabs, and shared buttons." },
  overview: { title: "Overview", description: "Metric cards, filters, follow-up queue, and performance tables." },
  salesRecords: { title: "Sales records", description: "Toolbar, search, filter chips, and empty states." },
  clientCare: { title: "Client care", description: "Table headings, empty states, and the Won-leads toggle wording. The on/off switch itself is under History & reports." },
  forms: { title: "Forms and dialogs", description: "Section titles and buttons on add, edit, activity, and merge dialogs. Field labels themselves are under Form fields." },
  history: { title: "History", description: "Headings and empty states on the Change history page. Lookback days are under History & reports." },
  reports: { title: "Reports", description: "Headings, custom date-range wording, and help text on the Reports page. Preset ranges and show/hide toggles are under History & reports." },
  calendar: { title: "Calendar", description: "Google Calendar sync labels, status copy, and event type wording. Connection, enable, calendar id, and templates are under the Calendar tab." },
  team: { title: "Team access", description: "Headings, form labels, and buttons on the Team access page." },
};

export const SCHEDULED_INTERPRETATION_SERVICE = "Scheduled Interpretation";
export const PENDING_STAGE = "Pending";
export const WON_STAGE = "Won";
export const CLOSED_STAGES = ["Won", "Lost", "Canceled"] as const;
export const CARE_ATTENTION_STATUSES = ["Needs attention", "At risk"] as const;
